# Generated by Django 5.1 on 2024-08-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categries'},
        ),
        migrations.AddField(
            model_name='quote',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
